project:
  type: website

website:
  title: "Posterior Musings"
  navbar: true
  page-footer:
    center: "© 2026 Edric Tam"

format:
  html:
    theme:
      light: [default, theme.scss]
      dark: [default, theme.scss, dark.scss]
    respect-user-color-scheme: true
